<?php

return [
    'menu'         => [
        'name'          => 'menu',
        'icon'          => 'fas fa-ellipsis-h',
        'active'        => true,
        'system'        => true,
        'sub_menu'      => [],
        'actions'       => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'hidden',
            8       => 'sort',
        ],
    ],
    'pages'         => [
        'name'         => 'pages',
        'icon'          => 'fas fa-pager',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'editPage',
            8       => 'updatePage',
            9       => 'hidden',
            10       => 'sort',
        ],
    ],
    'sliders'         => [
        'name'          => 'sliders',
        'icon'          => 'fas fa-sliders-h',
        'active'        => true,
        'system'        => false,
        'sub_menu'      => [],
        'actions'       => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'hidden',
            8       => 'sort',
        ],
    ],
    'reviews'         => [
        'name'          => 'reviews',
        'icon'          => 'fas fa-comments',
        'active'        => true,
        'system'        => false,
        'sub_menu'      => [],
        'actions'       => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'hidden',
            8       => 'sort',
        ],
    ],
    'articles'         => [
        'name'         => 'articles',
        'active'        => false,
        'system'        => false,
        'sub_menu'           => [],
        'actions'         => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'hidden',
        ],
    ],
    'contact'         => [
        'name'         => 'contact',
        'icon'          => 'fas fa-pager',
        'active'        => false,
        'system'        => false,
        'sub_menu'           => [],
        'actions'         => [
            1       => 'index',
            2       => 'updateMarker',
            3       => 'deleteMarker',
            4       => 'saveDataCoordinates',
            5       => 'sort',
        ],
    ],
    'file_store'         => [
        'name'         => 'file_store',
        'icon'          => 'fas fa-database',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            1       => 'index',
            2       => 'upload',
            3       => 'delete',
        ],
    ],
    'languages'         => [
        'name'         => 'languages',
        'icon'          => 'fas fa-language',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'hidden',
        ],
    ],
    'helper_fields'         => [
        'name'         => 'helper_fields',
        'icon'          => 'fas fa-tools',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            1       => 'index',
            2       => 'add',
            3       => 'create',
            4       => 'edit',
            5       => 'update',
            6       => 'delete',
            7       => 'hidden',
        ],
    ],
];