<?php

return [
    'menu'         => [
        'name'          => 'menu',
        'icon'          => 'fas fa-ellipsis-h',
        'active'        => true,
        'system'        => true,
        'sub_menu'      => [],
        'actions'       => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
            'sort' => 'sort',
        ],
    ],
    'pages'         => [
        'name'         => 'pages',
        'icon'          => 'fas fa-pager',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
            'sort' => 'sort',
            'editPage' => 'editPage',
        ],
    ],
    'sliders'         => [
        'name'          => 'sliders',
        'icon'          => 'fas fa-sliders-h',
        'active'        => true,
        'system'        => false,
        'sub_menu'      => [],
        'actions'       => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
            'sort' => 'sort',
        ],
    ],
    'reviews'         => [
        'name'          => 'reviews',
        'icon'          => 'fas fa-comments',
        'active'        => true,
        'system'        => false,
        'sub_menu'      => [],
        'actions'       => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
            'sort' => 'sort',
        ],
    ],
    'articles'         => [
        'name'         => 'articles',
        'active'        => false,
        'system'        => false,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
        ],
    ],
    'contact'         => [
        'name'         => 'contact',
        'icon'          => 'fas fa-pager',
        'active'        => false,
        'system'        => false,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            'write' => 'saveDataCoordinates',
            'edit' => 'updateMarker',
            'delete' => 'deleteMarker',
            'sort' => 'sort',
        ],
    ],
    'gallery'         => [
        'name'         => 'gallery',
        'icon'          => 'fas fa-palette',
        'active'        => false,
        'system'        => false,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            // 'write' => 'upload',
            // 'delete' => 'delete',
        ],
    ],
    'file_store'         => [
        'name'         => 'file_store',
        'icon'          => 'fas fa-database',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            'write' => 'upload',
            'delete' => 'delete',
        ],
    ],
    'languages'         => [
        'name'         => 'languages',
        'icon'          => 'fas fa-language',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
        ],
    ],
    'helper_fields'         => [
        'name'         => 'helper_fields',
        'icon'          => 'fas fa-tools',
        'active'        => true,
        'system'        => true,
        'sub_menu'           => [],
        'actions'         => [
            'read' => 'index',
            'write' => 'add',
            'edit' => 'edit',
            'delete' => 'delete',
        ],
    ],
];
